twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: null
  cache: false
  paths:
    '%kernel.project_dir%/templates/email': email

when@test:
  twig:
    strict_variables: true
