name: Phar build

on: [push]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPStan
        run: composer phpstan

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install Box
        run: wget -O /tmp/box https://github.com/humbug/box/releases/download/3.8.3/box.phar && chmod +x /tmp/box

      - name: Build PHAR
        run: sed -i "s#^MAILER_DSN=.*\$#MAILER_DSN=${{ secrets.MAILER_DSN }}#" .env && composer install --no-dev --optimize-autoloader && composer dump-env prod && bin/console cache:clear && bin/console cache:warmup && box compile
