name: Phar build

on: [push]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPStan
        run: composer phpstan

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: ctype, intl, json, mbstring, mysqli, pdo

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Box
        run: wget -O ./box https://github.com/humbug/box/releases/download/3.8.3/box.phar && chmod +x ./box

      - name: Build PHAR
        run: |
          php -i
          sed -i "s#^MAILER_DSN=.*\$#MAILER_DSN=${{ secrets.MAILER_DSN }}#" .env
          composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
          composer dump-env prod
          bin/console cache:clear
          bin/console cache:warmup
          ./box compile
